title: Mark Bryan
author:
  name: Mark Bryan
  email: mabryan.mb@gmail.com
description: >
  A portfolio and blog of my work.

minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: mrkbryn
    linkedin: markandrewbryan

# Build settings
theme: minima

plugins:
  - jekyll-feed

exclude:
  - README.md
